version: "3.8"

services:
  report_siem_report_interface:
    build:
      dockerfile: ./docker/backend.dockerfile
      context: .
    container_name: report_interface_api
    env_file: .env
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 7000 --reload"
    ports:
      - "7006:7000"
    networks:
      - report
    volumes:
      - .:/code

networks:
  report:
    external: true
