"""initial reports

Revision ID: 0001
Revises: 
Create Date: 2023-03-16 16:49:03.938718

"""
from datetime import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    report_type = op.create_table('report_type',
                                  sa.Column('created_at', sa.DateTime(), nullable=True),
                                  sa.Column('updated_at', sa.DateTime(), nullable=True),
                                  sa.Column('created_by', sa.String(length=50), nullable=True),
                                  sa.Column('id', sa.Integer(), nullable=False),
                                  sa.Column('name', sa.String(length=255), nullable=True),
                                  sa.Column('code_name', sa.String(length=30), nullable=True),
                                  sa.PrimaryKeyConstraint('id'),
                                  schema='report_interface'
                                  )
    op.create_table('report',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(length=50), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['type'], ['report_interface.report_type.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='report_interface'
                    )
    # ### end Alembic commands ###

    op.bulk_insert(
        report_type,
        [
            {
                'created_at': datetime.now(),
                'updated_at': datetime.now(),
                'created_by': None,
                'id': 1,
                'name': 'Alerts',
                'code_name': 'alerts'
            },
            {
                'created_at': datetime.now(),
                'updated_at': datetime.now(),
                'created_by': None,
                'id': 2,
                'name': 'Top10 login failures',
                'code_name': 'top10_login_failures'
            },
            {
                'created_at': datetime.now(),
                'updated_at': datetime.now(),
                'created_by': None,
                'id': 3,
                'name': 'Main triggered rules',
                'code_name': 'main_triggerd_rules'
            },
            {
                'created_at': datetime.now(),
                'updated_at': datetime.now(),
                'created_by': None,
                'id': 4,
                'name': 'Registered events',
                'code_name': 'registered_events'
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report', schema='report_interface')
    op.drop_table('report_type', schema='report_interface')
    # ### end Alembic commands ###
